version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
      - image: circleci/mongo:latest
    steps:
      - checkout
      - restore_cache:
          key: meteor-release-{{ checksum ".meteor/release" }}-{{ checksum ".circleci/config.yml" }}
      - restore_cache:
          key: meteor-packages-{{ checksum ".meteor/versions" }}-{{ checksum ".circleci/config.yml" }}
      - restore_cache:
          key: npm-packages-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: install build essentials
          command: sudo apt-get install -y build-essential
      - run:
          name: install Meteor
          command: |
            if [ -e ~/.meteor/meteor ]; then
              command -v meteor >/dev/null 2>&1 || sudo ln -sv ~/.meteor/meteor /usr/local/bin/meteor
            else
              command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com | /bin/sh
            fi
      - run:
          name: check versions
          command: |
            echo "Meteor versions:"
            meteor --version
            echo "Meteor node version:"
            meteor node -v
            echo "Meteor npm version:"
            meteor npm -v
      - run:
          name: install npm packages
          command: meteor npm install
      - run:
          name: fix broken npm and install npm packages
          command: |
            rm -rf ~/.npm ./node_modules
            meteor npm install
          when: on_fail
      - run:
          name: list meteor installed package
          command: meteor list
      - run:
          name: setup locale
          command: |
              sudo locale-gen en_US.UTF8
              sudo localedef -i en_US -f UTF-8 en_US.UTF-8
          environment:
              LANG: en_US.UTF-8
              LANGUAGE: en_US.UTF-8
              LC_ALL: en_US.UTF-8
      - run:
          name: code linting
          command: meteor npm run lint
      - run:
          name: run all unit tests
          command: meteor npm run test:units
      - run:
          name: run integration tests
          command: meteor npm test
          environment:
              MONGO_URL: mongodb://localhost:27017/db
      - save_cache:
          key: meteor-release-{{ checksum ".meteor/release" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.meteor/
      - save_cache:
          key: meteor-packages-{{ checksum ".meteor/versions" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - .meteor/
      - save_cache:
          key: npm-packages-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ./node_modules/
            - ~/.npm/
